apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability-operator
images:
- name: observability-operator
  newName: quay.io/afalossi/observability-operator
  newTag: 1.1.0-dev-0.1.23
commonAnnotations:
  package-operator.run/phase: operator
resources:
- ../../operator/
